### ISSUE TITLE
UI dimensions never change

### ISSUE THREAD

**Issue by ohthehugemanatee** [eul-im/eul#3]
When I start the client, it sets a relatively small size for itself, which seems reasonable for the initial setup. But when I resize the window around it, the UI doesn't resize along with it.  Screenshot explains it best: https://www.dropbox.com/s/qx9wwvwdeo0owd5/Screenshot_2017-07-27-09.52.png?dl=0

Ubuntu 17.04, i3wm, Dell XPS 13 9360. Starting from (zsh) terminal.

**Comment by voltapp2** [comment]
Hi @ohthehugemanatee,

Thanks a lot for your bug reports.

Yes, it's currently not possible to resize the application due to certain limitations of the current chat drawing algorithm. This will be fixed in early August.

In traditional WMs the window is simply not resizable, but it's very ugly in a tiling WM, sorry about that.

**Comment by ohthehugemanatee** [comment]
Makes sense. Thanks!

**Comment by j6k4m8** [comment]
Do you have an update on this? This is probably the only thing standing in the way of using this as my primary messaging app.

**Comment by voltapp2** [comment]
Sorry for the ridiculous delay. This was fixed in 0.35.
