### ISSUE TITLE
Links to site are broken

### ISSUE THREAD

**Issue by IanOlin** [eul-im/eul#88]
The github has a hyperlink to eul.im which seems to be down and the patreon has a link that appears to be to volt.ws but is actually a link to eul.im. Eul.im seems to no longer redirect to volt.ws

**Comment by dwainetrain** [comment]
Yes, it seems the original domain has been appropriated by a malware propagator. Too bad, since it's appearing at the top of search results thanks to its listing on hacker news. Is there a way to report this?

**Comment by voltapp2** [comment]
Sorry for the ridiculous delay and not announcing this pretty pretty important change.

I changed the name to Volt back in May and set up a redirect. But I'm embarrassed to say that I didn't renew the .im domain in time. I had this bad habit of renewing domains 1-2 days before the expiry date. Sometimes I would even do it after (you have 30 days to that).

Turned out .im domains are much stricter. You have to renew 3 days before the expiry, and if you don't, it's gone. Nothing you can do about it.

I've updated the Patreon link.
